language: node_js
node_js:
- '6'
- node
sudo: required
services:
- docker
before_install:
- npm install -g npm@'>=2.13.5'
deploy:
  provider: npm
  email: xo-npm.group@xogrp.com
  api_key:
    secure: Vtj1etrDCFuLVT/1zdHffxZBLAa6cvpNBwnvN95UVWKrdsCyd1oQYov7vr9vsIZaPF2ETWyFnqLOvRgzMgB7TiqGgNvuftDR5ZQ3jewshgVB5WXx2pdgeBg/30ZwanBVRegSlaX2/OnoJxNRendvJzl7hhoQS50OgeL4e3GuKWa3XEYt241cPEy0je3FSNODnRv7kilb0pI7nBwxRqcPcM7ouB5p5wIGCdHFbVzAdSvpK9tT4WNybVaDnE3Km6SRP8aDrOgxuxoVnnD97x+uxdOW+/rjxNDyiiBxhO06uDsbjmZA29ReNJVng2MFLYuOMtvlTK8m2MeYbVpZlOhLf32MRHQzJSawNR4k38jwrQExLIp/XOlaziEfpSF/pmKv0NJuL362Spg/Ps3ZOb/Ov1XGRcWGrg0A4nlZu0/X5syaREy1mOFjv27KYkNBhadwtJ3tPQGySBcTGbo5PJsCOAyphWuzdojwYZDehdvBv1HpcjuCBMvvV8ckuQ/S5CXGWGBZHJp1Ev1swKv8bb5O5es/t6FHm2PWJcjLWr6kyvjAoic6F8h3QSUR+d3Yqf8+Lu3HCRny1GZHdS3jXhg4SdBsuhjM+bMGQHyxphXB9kd4kOPzeVwfyKfQa0D/kw2G9YmZGfkE+I271iiUdkQD92koJOEnkQJSmZTYx74erYo=
  on:
    tags: true
    repo: xogroup/helm-chart-s3-publisher
notifications:
  slack:
    secure: I0R0m/Mz6pP7vZLaqRP3RwtaiI6lbpcfNpU1qUFMB4JgvHuqLEJyqUF/ayvph3wvCFeQTRkNX7Rot+II5kum71eM9T4yqxc/CBjDEoHFEVQ0G9sweeXMfZp1lukVyWnZXDgZSjTu8Ml7sItsEh8W5wJByjvvV2qdoBT8mn4kfAN+qAxLQUt5ZjsB13TLA3At16fGMPg170FCrtHsyLt2lfFW0bRhUvT8z1aTkn+7wuyVpamrt2l3PpJVgyJTUD0GuHUxBEIkv47fzSU/NmXFUw3e+Of8+AnB3LGFUK6CP42a50sbCKB7R0uWLLTXCDSaNLq6k3pu0lRytX0pTvZZR2hcki7VFbWMFl0FvKK7JAmQihJk9cxNY8URfpoNu7hXpeWXz+DU57MK/yYmwwmm/WxssFKuGmOgS1HU2n0sunB1OV9xJPu3yy7fr7raUZZvpJp8QRwWJIvBJprm0W+Oq6aDoagMZ/J5WCq/ThcnTmNBBFX+SlRfdzpq7NHtCB/TQeA61sl0+68G6YTIwtQ7ubIfT9EbMZgKCg6aUXSiOAXsT+JjPZEXk9CJURcxAihrvEKTh7Gs5rGMP27Zw8yT6N3uxrK5vitXuAkOXUdmZetbs1mBUrI+FVY21ey/gxTtLQlUTGPlf3DJvXBBpmjrZGlAHlit6zZQEENLgzxSfhA=
